// data.ts
export const data = [
  { label: "Alfalfa Sprouts", description: "Nutritious sprouts from the alfalfa plant." },
  { label: "Apple", description: "A sweet, crisp fruit that is great for snacking." },
  { label: "Apricot", description: "A small, juicy fruit with a sweet and tart flavor." },
  { label: "Artichoke", description: "A spiky vegetable often enjoyed with butter or dips." },
  { label: "Asian Pear", description: "A crisp, juicy fruit that is a cross between an apple and a pear." },
  { label: "Asparagus", description: "A green stalk vegetable often grilled or roasted." },
  { label: "Atemoya", description: "A hybrid fruit with a creamy, sweet taste." },
  { label: "Avocado", description: "A creamy fruit rich in healthy fats, popular in guacamole." },
  { label: "Bamboo Shoots", description: "Young shoots of bamboo, used in Asian cuisine." },
  { label: "Banana", description: "A tropical fruit high in potassium and convenient for snacking." },
  { label: "Bean Sprouts", description: "Crisp sprouts commonly used in Asian dishes." },
  { label: "Beans", description: "A versatile legume available in many varieties." },
  { label: "Beets", description: "A root vegetable with a deep red color and earthy flavor." },
  { label: "Belgian Endive", description: "A leafy vegetable with a slightly bitter taste." },
  { label: "Bell Peppers", description: "Crunchy vegetables available in a variety of colors." },
  { label: "Bitter Melon", description: "A tropical fruit known for its strong bitter flavor." },
  { label: "Blackberries", description: "Dark berries that are juicy and slightly tart." },
  { label: "Blueberries", description: "Small, sweet berries packed with antioxidants." },
  { label: "Bok Choy", description: "A Chinese cabbage with crisp stems and tender leaves." },
  { label: "Boniato", description: "A sweet potato variety with a drier texture." },
  { label: "Boysenberries", description: "A cross between blackberries and raspberries." },
  { label: "Broccoflower", description: "A cross between broccoli and cauliflower." },
  { label: "Broccoli", description: "A green vegetable rich in vitamins and fiber." },
  { label: "Brussels Sprouts", description: "Small, cabbage-like vegetables, often roasted." },
  { label: "Cabbage", description: "A leafy vegetable used in salads, slaws, and stir-fries." },
  { label: "Cactus Pear", description: "A sweet fruit from the prickly pear cactus." },
  { label: "Cantaloupe", description: "A juicy orange melon that is sweet and fragrant." },
  { label: "Carambola", description: "Also known as starfruit, a sweet and tart tropical fruit." },
  { label: "Carrots", description: "A crunchy orange root vegetable." },
  { label: "Casaba Melon", description: "A mild-flavored melon with yellow skin." },
  { label: "Cauliflower", description: "A white vegetable that can be roasted or steamed." },
  { label: "Celery", description: "A crunchy vegetable often eaten as a snack or in salads." },
  { label: "Chayote", description: "A green, wrinkled squash commonly used in Latin American dishes." },
  { label: "Cherimoya", description: "A tropical fruit with a custard-like texture." },
  { label: "Cherries", description: "Small, sweet or tart stone fruits." },
  { label: "Coconuts", description: "A tropical fruit known for its water and creamy flesh." },
  { label: "Collard Greens", description: "A leafy green vegetable rich in nutrients." },
  { label: "Corn", description: "A staple grain often enjoyed on the cob or as popcorn." },
  { label: "Cranberries", description: "Tart red berries often used in sauces and juices." },
  { label: "Cucumber", description: "A refreshing green vegetable, commonly eaten raw." },
  { label: "Dates", description: "Sweet, chewy fruits from the date palm." },
  { label: "Dried Plums", description: "Sweet and chewy, also known as prunes." },
  { label: "Eggplant", description: "A versatile vegetable often used in Mediterranean dishes." },
  { label: "Endive", description: "A leafy vegetable with a slightly bitter taste." },
  { label: "Escarole", description: "A type of leafy green with a mild flavor." },
  { label: "Feijoa", description: "A green, tangy fruit native to South America." },
  { label: "Fennel", description: "A vegetable with a mild, licorice-like flavor." },
  { label: "Figs", description: "Sweet, soft fruits often enjoyed dried or fresh." },
  { label: "Garlic", description: "A pungent bulb used to flavor many dishes." },
  { label: "Gooseberries", description: "Tart green or red berries, often used in jams." },
  { label: "Grapefruit", description: "A citrus fruit with a sweet and tart flavor." },
  { label: "Grapes", description: "Small, juicy fruits that can be eaten fresh or dried into raisins." },
  { label: "Green Beans", description: "Crunchy green vegetables often cooked or eaten raw." },
  { label: "Green Onions", description: "A mild onion variety with edible green tops." },
  { label: "Greens", description: "A general term for leafy vegetables." },
  { label: "Guava", description: "A tropical fruit with pink or white flesh and a sweet taste." },
  { label: "Honeydew Melon", description: "A sweet, green-fleshed melon." },
  { label: "Iceberg Lettuce", description: "A crisp, pale green lettuce used in salads." },
  { label: "Kale", description: "A nutrient-dense leafy green vegetable." },
  { label: "Kiwi", description: "A small, brown-skinned fruit with bright green flesh." },
  { label: "Lemon", description: "A citrus fruit with a tart, refreshing flavor." },
  { label: "Lime", description: "A green citrus fruit with a sour taste." },
  { label: "Mango", description: "A tropical fruit with sweet, juicy flesh." },
  { label: "Onion", description: "A bulb vegetable with a pungent flavor, used in many dishes." },
  { label: "Orange", description: "A citrus fruit known for its sweet and tangy taste." },
  { label: "Papaya", description: "A tropical fruit with orange flesh and black seeds." },
  { label: "Peach", description: "A sweet, juicy fruit with fuzzy skin." },
  { label: "Pear", description: "A juicy fruit with a soft, buttery texture." },
  { label: "Pineapple", description: "A tropical fruit with a sweet, tangy flavor." },
  { label: "Plum", description: "A stone fruit that is sweet and juicy." },
  { label: "Potato", description: "A starchy root vegetable that is versatile in cooking." },
  { label: "Spinach", description: "A leafy green vegetable rich in iron." },
  { label: "Strawberry", description: "A sweet, red berry often eaten fresh." },
  { label: "Tomato", description: "A juicy, red fruit often used in cooking." },
  { label: "Watermelon", description: "A large, juicy melon with green rind and red flesh." },
  { label: "Zucchini", description: "A green summer squash used in various dishes." },
];
